keys:
  - &nixos age1al4h6x4g2vhyz357n6hmk9a7g9gdjggettkcu2xl0gkkgnd7g5yqxgzp26
  - &serverless age1lxxlthd6jzlz6h2vez3490cwrs25635yxn40n7kxl3h8k9dt8f3qq7tna3

creation_rules:
  - path_regex: secrets/nixos\.yaml$
    key_groups:
      - age:
          - *nixos
  - path_regex: secrets/attic\.yaml$
    key_groups:
      - age:
          - *nixos
          - *serverless
