ssh-github: ENC[AES256_GCM,data:zV5eZ/GvlGCQx/PKNAoel3XLPegBqfuWXsLm0RCsnCbN4lwv0esAxy2dt4egt+lrh4akhVWquwIU0J0K5Uirwpgb9TiV58mn5gQMQogR/2t8KZA6qr+FB6gq/LRLDqaW7teQw3rqkFAEuQcif4GV3T3AI4+6F5SImxcwcIVKLU8om7A8tYeBxdzlgrYMsbOD9UAK59ZG1xKizwzY59p72k4J7pAeXwozkEQb3fputGMAS0uYoncalY7PKaDgTd3KFaj07wWYe2GyF5oLK4sUO8NTsR2t3czIUuQKDWKUqc48FNES7OeqWTgKOBZS098MX2XJNn5FgUvYAzcE/nkIxzNGYm31ZEFpnBNV7btOW8rl4rlMXNRgK1mIDH3Pp/q/gR5ZllERntEkdTSd9ZUshX1uO/0yktMEpsaDwOzuI6aVPWNaWDKeKPh8tJ6Ydj8b/PzXgWIbpUGgzN2E3lVuKLAIpvfiV2O/YN9XfdIhHcg0Ly37CebzUkytiCtKoZ3yr8UKK3UA+rnajPWm99S7PjpLuXOzhVmMQ8zOBXyoEEQD92w=,iv:ZobBN+QvGy7IVyhAlOKV1GSZ03oPjJtcCyFMOH0vAGg=,tag:/NijvTxb61TF90fMqfFYqA==,type:str]
ssh-gitlab: ENC[AES256_GCM,data:dr7avCOub/muNA66ZeLdZGecP8aUn/07yn8PF6CMLfnC4XBi9nIIDHFlTMj782ZZDhCuWzyWV4uqLpRPiCdQ/HHB4ksFVxfNkGFyX12Gy2Am5OOXXN/k5aFYJtAaz+xh+O0GiJ8GVKQ3GueW5rmEWUzbZf0zjG4CkBuNUpu50EWjpx42tYzC+IUIA8o5zepdenA1Jh2bGcP4DsxnHHqdJ9DrSGqVqTOChm6ruCp43uVDD6RZrgKTegQKGT1dWk+c2jg1bQSKag5xTCAutFAbpV8VvmNyOlqqHE1IznLrdR9If90XlpmtXUFLog3jTpMrdQBtFIfjEEkndRPYCg8FZXRTnQkGc2wY82NusyBtqexbRlDEliKDFZcgW8CKsYumgf82p15NHj5JkDGxnwa8wSgMNzIrB47l4Veu1VvBiXII33TKZTVGZDJm9ganJ/HH00H2mjRH0iRHuXDgDab2OyC/iSjsb/k4V7iD/rSd2jbmVKvOcBfZeCexYPPrYwuV898RkzTplOe4JEFKeF2A80kgiv4e6R0fD25BAakCn2BnsHQ=,iv:Mb/oTrSUBBtUnIDzK0zHqXJdYs0zyojv28+aKelwXys=,tag:bJY4Sn1HUl57YFFagH3IzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMDVjT0pLdHpFZjhTOHN6
            MHBUMERLc1QrWW5JUmppNm1PRmhoUzZkYmdZCkswYUxxK2Iwc3pFWlNyRVovb0Qy
            THhXeVg0ZWk1TTJOQVhpd2d0YkJJTVUKLS0tICtJZ2xlREtTeEFZWGtmbi9WTmFk
            cnJGS1FTanNQSXhGTzJaQS9ESmdpVFkKRIu2DpqVDG2jHyD9Y3AiCLxq6jqW0xo7
            P/SyogkX6pYGDTGZ2j1V90i7ATyYpoJc1KWGeIsnFmonYZuUnIAAsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1al4h6x4g2vhyz357n6hmk9a7g9gdjggettkcu2xl0gkkgnd7g5yqxgzp26
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N1FqQTBIRUw2M1V3d3BU
            ZVJMYzZDV2FCT0c1a0JmTk5xZWROeEExZEZNCkVRK1BUWnNZZlMrVXVjYnh0a2th
            Nlo5TnNiWXpoVXhNOEZVOG83L2tJQ1kKLS0tIGN3bjZjUG5mS0tCMitRUlFjM3JV
            S2hNa2FlcTA2U3VlNVN2YlpKQzFpQk0Kl9KznTr0e6UvzH8wesWMXF3Q/QNDUk1Z
            Z/pRGbefyGk6f/5/cVifGqVubhAZs4XR/e7y1M41x46GC/mSyHz8FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rahl2wwkqqm3xr8w3cjwevmf9jv64dklezhq76urzp60drfgcymqv96vc9
    lastmodified: "2026-10-07T10:43:51Z"
    mac: ENC[AES256_GCM,data:L5NjRHx51c+y7kAUObYhNkSnNB8V0vBXXMQcQhR9N9hzk9rjs7rLMFh9L0uhLtEep9QPgLJBrR0CIlsfu/1+D9Aigrou0P+DPSuhWyRH9MtI8OY8rVjqTSFjHLVoBX/jn5K6QDWAstZn1hTKfE1rROtXGJgmgRgkE2/5M/H91Bk=,iv:mfyFyz9WwPP2C2/RCK9LAHWy4vjLu/DYDsA26w6mmrw=,tag:VTkJgMWAQox89TPIIJzEgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
